# ITMGT 25.03 EE
# Assignment 3B

This is a data-cleaning assignment and is the second of two parts. This notebook is uploaded to our Github repository along with a csv of fake, dirty data called **recweekdata.csv**.

In addition, you have a new file called **studentprofiles.csv** which has first and last names plus the genders of the students.

The output of this assignment is to convert recweekdata.csv into processable data for statistics. Submit the following files through GitHub:
1. A cleaned recweekdata.csv called **cleanrecweekdata3b.csv** **(5 points)**
2. This notebook, containing the code (properly commented) that you used to clean the data **(5 points)**
3. An html file of summary statistics from each column called **stats3b.html**. The requirements for the summary statistics are described below. **(10 points)**

The outputs are similar to that of Assignment 3A, except that you will now use Pandas instead of Python lists.

This entire assignment (3B) is worth 20 points.

Upload your output files to your Github repositories. Make sure to send an email to **joben.ilagan@gmail.com** once you're done.

This assignment is due on **Monday, July 9, 2019** at 12:00NN.

Note: I understand you all need to review for LT 2. Think of this Assignment as practice. It's not meant to take you as long as 3A.

#### Bonus Points:
* +2 if submitted over (or before) the weekend (July 13-14)
* +2 if CSS and div tags are used (but please don't spend too much time on this because you still need to review for the Long Test)

In [22]:
import pandas as pd

In [23]:
recweek = pd.read_csv("recweekdata.csv")

In [24]:
recweek.head()

firstname   lastname birthmonth  birthday  birthyear      course  \
0     name1  lastname1         11        26       1998       BS LM   
1     name2  lastname2        May        26       2001  Management   
2     name3  lastname3          5        16       1997      BS CTM   
3     name4  lastname4        Dec         9         97      BS ITE   
4     name5  lastname5        Sep         5         97      BS CTM   

        phonenumber  
0  +63 918 302 6210  
1      927 212 6276  
2  +63 918 253 7017  
3      918 714 4360  
4  +63 927 462 1674

In [25]:
recweek.tail()

firstname      lastname birthmonth  birthday  birthyear  \
2995  name2996  lastname2996      March        28         97   
2996  name2997  lastname2997        May        19       1998   
2997  name2998  lastname2998       July         3         98   
2998  name2999  lastname2999         12         2         98   
2999  name3000  lastname3000        Jul        13       1997   

                course       phonenumber  
2995            BS CTM      917 795 5051  
2996                LM      917 445 3378  
2997               ITE      917 154 5694  
2998                ME      927 497 8977  
2999  Legal Management  +63 918 719 7624

# Month Cleaning

In [26]:
months = {"January":["1","Jan","January"],
          "February":["2","Feb","February"],
          "March":["3","Mar","March"],
          "April":["4","Apr","April"],
          "May":["5","May"],
          "June":["6","Jun","June"],
          "July":["7","Jul","July"],
          "August":["8","Aug","August"],
          "September":["9","Sep","September"],
          "October":["10","Oct","October"],
          "November":["11","Nov","November"],
          "December":["12","Dec","December"]}

In [27]:
def fix_month(month):
    for i in months:
        if month in months[i]:
            return i
fix_month("11")

'November'

In [28]:
import re
recweek.loc[:,"birthmonth"] = recweek.loc[:,"birthmonth"].apply(lambda x: fix_month(x))
recweek

firstname      lastname birthmonth  birthday  birthyear  \
0        name1     lastname1   November        26       1998   
1        name2     lastname2        May        26       2001   
2        name3     lastname3        May        16       1997   
3        name4     lastname4   December         9         97   
4        name5     lastname5  September         5         97   
5        name6     lastname6      March         2       1999   
6        name7     lastname7   November        10         98   
7        name8     lastname8     August        28         99   
8        name9     lastname9       July        10         97   
9       name10    lastname10  September        14       2001   
10      name11    lastname11   December         8         98   
11      name12    lastname12        May         4         97   
12      name13    lastname13    January        28       1999   
13      name14    lastname14    January        11       1999   
14      name15    lastname15       June         6         98   
15      name16    lastname16      April        20         99   
16      name17    lastname17    January         3         97   
17      name18    lastname18      April         8       1997   
18      name19    lastname19   December        28       1997   
19      name20    lastname20      March        10         97   
20      name21    lastname21       July        13         99   
21      name22    lastname22  September        15       1999   
22      name23    lastname23      April        15         97   
23      name24    lastname24    October         1         97   
24      name25    lastname25        May         6         97   
25      name26    lastname26   December         5       1999   
26      name27    lastname27      March         4       1997   
27      name28    lastname28   November        10       2000   
28      name29    lastname29    October        10       1999   
29      name30    lastname30        May        28       1999   
...        ...           ...        ...       ...        ...   
2970  name2971  lastname2971   February        25         97   
2971  name2972  lastname2972        May        14       1998   
2972  name2973  lastname2973    October         9       1999   
2973  name2974  lastname2974     August        12       1999   
2974  name2975  lastname2975   November        18       1997   
2975  name2976  lastname2976       July        24       1998   
2976  name2977  lastname2977        May        26         98   
2977  name2978  lastname2978    October        26         99   
2978  name2979  lastname2979   February        13       1997   
2979  name2980  lastname2980       July         3         99   
2980  name2981  lastname2981   February        17       1998   
2981  name2982  lastname2982      March        28       2000   
2982  name2983  lastname2983   December         3         98   
2983  name2984  lastname2984   November        13       2000   
2984  name2985  lastname2985   February        23         99   
2985  name2986  lastname2986      March         2       1999   
2986  name2987  lastname2987    October         6         97   
2987  name2988  lastname2988   February        20       1997   
2988  name2989  lastname2989    January        17       1999   
2989  name2990  lastname2990       July        14         97   
2990  name2991  lastname2991       July        27       2000   
2991  name2992  lastname2992      March        26         99   
2992  name2993  lastname2993      April         1       2000   
2993  name2994  lastname2994      April        10         99   
2994  name2995  lastname2995        May        21         97   
2995  name2996  lastname2996      March        28         97   
2996  name2997  lastname2997        May        19       1998   
2997  name2998  lastname2998       July         3         98   
2998  name2999  lastname2999   December         2         98   
2999  name3000  lastname3000       July        13       1997   

                                    

# Year Cleaning

In [29]:
# change birthyear type from integer to string
recweek.loc[:,"birthyear"]=recweek.loc[:,"birthyear"].apply(str)
recweek.dtypes

firstname      object
lastname       object
birthmonth     object
birthday        int64
birthyear      object
course         object
phonenumber    object
dtype: object

In [30]:
recweek.loc[:,"birthyear"]= recweek.loc[:,"birthyear"].str.replace("^99$", "1999",regex=True).copy()
recweek.loc[:,"birthyear"]= recweek.loc[:,"birthyear"].str.replace("^98$", "1998",regex=True).copy()
recweek.loc[:,"birthyear"]= recweek.loc[:,"birthyear"].str.replace("^97$", "1997",regex=True).copy()
recweek.loc[:,"birthyear"]= recweek.loc[:,"birthyear"].str.replace("^00$", "2000",regex=True).copy()
recweek.loc[:,"birthyear"]= recweek.loc[:,"birthyear"].str.replace("^01$", "2001",regex=True).copy()

recweek

firstname      lastname birthmonth  birthday birthyear  \
0        name1     lastname1   November        26      1998   
1        name2     lastname2        May        26      2001   
2        name3     lastname3        May        16      1997   
3        name4     lastname4   December         9      1997   
4        name5     lastname5  September         5      1997   
5        name6     lastname6      March         2      1999   
6        name7     lastname7   November        10      1998   
7        name8     lastname8     August        28      1999   
8        name9     lastname9       July        10      1997   
9       name10    lastname10  September        14      2001   
10      name11    lastname11   December         8      1998   
11      name12    lastname12        May         4      1997   
12      name13    lastname13    January        28      1999   
13      name14    lastname14    January        11      1999   
14      name15    lastname15       June         6      1998   
15      name16    lastname16      April        20      1999   
16      name17    lastname17    January         3      1997   
17      name18    lastname18      April         8      1997   
18      name19    lastname19   December        28      1997   
19      name20    lastname20      March        10      1997   
20      name21    lastname21       July        13      1999   
21      name22    lastname22  September        15      1999   
22      name23    lastname23      April        15      1997   
23      name24    lastname24    October         1      1997   
24      name25    lastname25        May         6      1997   
25      name26    lastname26   December         5      1999   
26      name27    lastname27      March         4      1997   
27      name28    lastname28   November        10      2000   
28      name29    lastname29    October        10      1999   
29      name30    lastname30        May        28      1999   
...        ...           ...        ...       ...       ...   
2970  name2971  lastname2971   February        25      1997   
2971  name2972  lastname2972        May        14      1998   
2972  name2973  lastname2973    October         9      1999   
2973  name2974  lastname2974     August        12      1999   
2974  name2975  lastname2975   November        18      1997   
2975  name2976  lastname2976       July        24      1998   
2976  name2977  lastname2977        May        26      1998   
2977  name2978  lastname2978    October        26      1999   
2978  name2979  lastname2979   February        13      1997   
2979  name2980  lastname2980       July         3      1999   
2980  name2981  lastname2981   February        17      1998   
2981  name2982  lastname2982      March        28      2000   
2982  name2983  lastname2983   December         3      1998   
2983  name2984  lastname2984   November        13      2000   
2984  name2985  lastname2985   February        23      1999   
2985  name2986  lastname2986      March         2      1999   
2986  name2987  lastname2987    October         6      1997   
2987  name2988  lastname2988   February        20      1997   
2988  name2989  lastname2989    January        17      1999   
2989  name2990  lastname2990       July        14      1997   
2990  name2991  lastname2991       July        27      2000   
2991  name2992  lastname2992      March        26      1999   
2992  name2993  lastname2993      April         1      2000   
2993  name2994  lastname2994      April        10      1999   
2994  name2995  lastname2995        May        21      1997   
2995  name2996  lastname2996      March        28      1997   
2996  name2997  lastname2997        May        19      1998   
2997  name2998  lastname2998       July         3      1998   
2998  name2999  lastname2999   December         2      1998   
2999  name3000  lastname3000       July        13      1997   

                                       course       phonenumber  
0                               

# Course Cleaning

In [31]:
courses = {"BS Communications Technology":["CTM","BS CTM","Communications Technology"],
           "BS Management Engineering":["ME","BS ME","Management Engineering"],
           "BS Management":["MGT","BS MGT","Management"],
           "BS Legal Management":["LM","BS LM","Legal Management"],
           "BS IT Entrepreneurship":["ITE","BS ITE","Information Technology Entrepreneurship"]}

In [32]:
def fix_course(course):
    for i in courses:
        if course in courses[i]:
            return i
fix_course("ME")

'BS Management Engineering'

In [33]:
recweek.loc[:,"course"] = recweek.loc[:,"course"].apply(lambda x: fix_course(x))
recweek

firstname      lastname birthmonth  birthday birthyear  \
0        name1     lastname1   November        26      1998   
1        name2     lastname2        May        26      2001   
2        name3     lastname3        May        16      1997   
3        name4     lastname4   December         9      1997   
4        name5     lastname5  September         5      1997   
5        name6     lastname6      March         2      1999   
6        name7     lastname7   November        10      1998   
7        name8     lastname8     August        28      1999   
8        name9     lastname9       July        10      1997   
9       name10    lastname10  September        14      2001   
10      name11    lastname11   December         8      1998   
11      name12    lastname12        May         4      1997   
12      name13    lastname13    January        28      1999   
13      name14    lastname14    January        11      1999   
14      name15    lastname15       June         6      1998   
15      name16    lastname16      April        20      1999   
16      name17    lastname17    January         3      1997   
17      name18    lastname18      April         8      1997   
18      name19    lastname19   December        28      1997   
19      name20    lastname20      March        10      1997   
20      name21    lastname21       July        13      1999   
21      name22    lastname22  September        15      1999   
22      name23    lastname23      April        15      1997   
23      name24    lastname24    October         1      1997   
24      name25    lastname25        May         6      1997   
25      name26    lastname26   December         5      1999   
26      name27    lastname27      March         4      1997   
27      name28    lastname28   November        10      2000   
28      name29    lastname29    October        10      1999   
29      name30    lastname30        May        28      1999   
...        ...           ...        ...       ...       ...   
2970  name2971  lastname2971   February        25      1997   
2971  name2972  lastname2972        May        14      1998   
2972  name2973  lastname2973    October         9      1999   
2973  name2974  lastname2974     August        12      1999   
2974  name2975  lastname2975   November        18      1997   
2975  name2976  lastname2976       July        24      1998   
2976  name2977  lastname2977        May        26      1998   
2977  name2978  lastname2978    October        26      1999   
2978  name2979  lastname2979   February        13      1997   
2979  name2980  lastname2980       July         3      1999   
2980  name2981  lastname2981   February        17      1998   
2981  name2982  lastname2982      March        28      2000   
2982  name2983  lastname2983   December         3      1998   
2983  name2984  lastname2984   November        13      2000   
2984  name2985  lastname2985   February        23      1999   
2985  name2986  lastname2986      March         2      1999   
2986  name2987  lastname2987    October         6      1997   
2987  name2988  lastname2988   February        20      1997   
2988  name2989  lastname2989    January        17      1999   
2989  name2990  lastname2990       July        14      1997   
2990  name2991  lastname2991       July        27      2000   
2991  name2992  lastname2992      March        26      1999   
2992  name2993  lastname2993      April         1      2000   
2993  name2994  lastname2994      April        10      1999   
2994  name2995  lastname2995        May        21      1997   
2995  name2996  lastname2996      March        28      1997   
2996  name2997  lastname2997        May        19      1998   
2997  name2998  lastname2998       July         3      1998   
2998  name2999  lastname2999   December         2      1998   
2999  name3000  lastname3000       July        13      1997   

                            course       phonenumber  
0              BS Legal Management  +63 918

# Number Cleaning

In [34]:
recweek.loc[:,"phonenumber"]= recweek.loc[:,"phonenumber"].str.replace("^\+63 ", "",regex=True).copy()
recweek.loc[:,"phonenumber"]= recweek.loc[:,"phonenumber"].str.replace("^9", "09",regex=True).copy()

recweek

firstname      lastname birthmonth  birthday birthyear  \
0        name1     lastname1   November        26      1998   
1        name2     lastname2        May        26      2001   
2        name3     lastname3        May        16      1997   
3        name4     lastname4   December         9      1997   
4        name5     lastname5  September         5      1997   
5        name6     lastname6      March         2      1999   
6        name7     lastname7   November        10      1998   
7        name8     lastname8     August        28      1999   
8        name9     lastname9       July        10      1997   
9       name10    lastname10  September        14      2001   
10      name11    lastname11   December         8      1998   
11      name12    lastname12        May         4      1997   
12      name13    lastname13    January        28      1999   
13      name14    lastname14    January        11      1999   
14      name15    lastname15       June         6      1998   
15      name16    lastname16      April        20      1999   
16      name17    lastname17    January         3      1997   
17      name18    lastname18      April         8      1997   
18      name19    lastname19   December        28      1997   
19      name20    lastname20      March        10      1997   
20      name21    lastname21       July        13      1999   
21      name22    lastname22  September        15      1999   
22      name23    lastname23      April        15      1997   
23      name24    lastname24    October         1      1997   
24      name25    lastname25        May         6      1997   
25      name26    lastname26   December         5      1999   
26      name27    lastname27      March         4      1997   
27      name28    lastname28   November        10      2000   
28      name29    lastname29    October        10      1999   
29      name30    lastname30        May        28      1999   
...        ...           ...        ...       ...       ...   
2970  name2971  lastname2971   February        25      1997   
2971  name2972  lastname2972        May        14      1998   
2972  name2973  lastname2973    October         9      1999   
2973  name2974  lastname2974     August        12      1999   
2974  name2975  lastname2975   November        18      1997   
2975  name2976  lastname2976       July        24      1998   
2976  name2977  lastname2977        May        26      1998   
2977  name2978  lastname2978    October        26      1999   
2978  name2979  lastname2979   February        13      1997   
2979  name2980  lastname2980       July         3      1999   
2980  name2981  lastname2981   February        17      1998   
2981  name2982  lastname2982      March        28      2000   
2982  name2983  lastname2983   December         3      1998   
2983  name2984  lastname2984   November        13      2000   
2984  name2985  lastname2985   February        23      1999   
2985  name2986  lastname2986      March         2      1999   
2986  name2987  lastname2987    October         6      1997   
2987  name2988  lastname2988   February        20      1997   
2988  name2989  lastname2989    January        17      1999   
2989  name2990  lastname2990       July        14      1997   
2990  name2991  lastname2991       July        27      2000   
2991  name2992  lastname2992      March        26      1999   
2992  name2993  lastname2993      April         1      2000   
2993  name2994  lastname2994      April        10      1999   
2994  name2995  lastname2995        May        21      1997   
2995  name2996  lastname2996      March        28      1997   
2996  name2997  lastname2997        May        19      1998   
2997  name2998  lastname2998       July         3      1998   
2998  name2999  lastname2999   December         2      1998   
2999  name3000  lastname3000       July        13      1997   

                            course    phonenumber  
0              BS Legal Management  0918 302 6

# Adding Genders

In [35]:
import pandas as pd
genders = pd.read_csv("studentprofiles.csv")

In [36]:
genders = genders.drop(columns=["lastname"])

In [37]:
final_recweek = pd.merge(recweek,genders, on = "firstname")
final_recweek

firstname      lastname birthmonth  birthday birthyear  \
0        name1     lastname1   November        26      1998   
1        name2     lastname2        May        26      2001   
2        name3     lastname3        May        16      1997   
3        name4     lastname4   December         9      1997   
4        name5     lastname5  September         5      1997   
5        name6     lastname6      March         2      1999   
6        name7     lastname7   November        10      1998   
7        name8     lastname8     August        28      1999   
8        name9     lastname9       July        10      1997   
9       name10    lastname10  September        14      2001   
10      name11    lastname11   December         8      1998   
11      name12    lastname12        May         4      1997   
12      name13    lastname13    January        28      1999   
13      name14    lastname14    January        11      1999   
14      name15    lastname15       June         6      1998   
15      name16    lastname16      April        20      1999   
16      name17    lastname17    January         3      1997   
17      name18    lastname18      April         8      1997   
18      name19    lastname19   December        28      1997   
19      name20    lastname20      March        10      1997   
20      name21    lastname21       July        13      1999   
21      name22    lastname22  September        15      1999   
22      name23    lastname23      April        15      1997   
23      name24    lastname24    October         1      1997   
24      name25    lastname25        May         6      1997   
25      name26    lastname26   December         5      1999   
26      name27    lastname27      March         4      1997   
27      name28    lastname28   November        10      2000   
28      name29    lastname29    October        10      1999   
29      name30    lastname30        May        28      1999   
...        ...           ...        ...       ...       ...   
2970  name2971  lastname2971   February        25      1997   
2971  name2972  lastname2972        May        14      1998   
2972  name2973  lastname2973    October         9      1999   
2973  name2974  lastname2974     August        12      1999   
2974  name2975  lastname2975   November        18      1997   
2975  name2976  lastname2976       July        24      1998   
2976  name2977  lastname2977        May        26      1998   
2977  name2978  lastname2978    October        26      1999   
2978  name2979  lastname2979   February        13      1997   
2979  name2980  lastname2980       July         3      1999   
2980  name2981  lastname2981   February        17      1998   
2981  name2982  lastname2982      March        28      2000   
2982  name2983  lastname2983   December         3      1998   
2983  name2984  lastname2984   November        13      2000   
2984  name2985  lastname2985   February        23      1999   
2985  name2986  lastname2986      March         2      1999   
2986  name2987  lastname2987    October         6      1997   
2987  name2988  lastname2988   February        20      1997   
2988  name2989  lastname2989    January        17      1999   
2989  name2990  lastname2990       July        14      1997   
2990  name2991  lastname2991       July        27      2000   
2991  name2992  lastname2992      March        26      1999   
2992  name2993  lastname2993      April         1      2000   
2993  name2994  lastname2994      April        10      1999   
2994  name2995  lastname2995        May        21      1997   
2995  name2996  lastname2996      March        28      1997   
2996  name2997  lastname2997        May        19      1998   
2997  name2998  lastname2998       July         3      1998   
2998  name2999  lastname2999   December         2      1998   
2999  name3000  lastname3000       July        13      1997   

                            course    phonenumber  gender  
0              BS Legal Management  09

In [38]:
final_recweek = final_recweek.loc[:,["firstname","lastname","gender","birthmonth","birthday","birthyear","course","phonenumber"]]
final_recweek


firstname      lastname  gender birthmonth  birthday birthyear  \
0        name1     lastname1  Female   November        26      1998   
1        name2     lastname2  Female        May        26      2001   
2        name3     lastname3  Female        May        16      1997   
3        name4     lastname4    Male   December         9      1997   
4        name5     lastname5  Female  September         5      1997   
5        name6     lastname6  Female      March         2      1999   
6        name7     lastname7  Female   November        10      1998   
7        name8     lastname8    Male     August        28      1999   
8        name9     lastname9    Male       July        10      1997   
9       name10    lastname10  Female  September        14      2001   
10      name11    lastname11    Male   December         8      1998   
11      name12    lastname12    Male        May         4      1997   
12      name13    lastname13  Female    January        28      1999   
13      name14    lastname14  Female    January        11      1999   
14      name15    lastname15    Male       June         6      1998   
15      name16    lastname16    Male      April        20      1999   
16      name17    lastname17  Female    January         3      1997   
17      name18    lastname18  Female      April         8      1997   
18      name19    lastname19    Male   December        28      1997   
19      name20    lastname20    Male      March        10      1997   
20      name21    lastname21  Female       July        13      1999   
21      name22    lastname22    Male  September        15      1999   
22      name23    lastname23    Male      April        15      1997   
23      name24    lastname24    Male    October         1      1997   
24      name25    lastname25    Male        May         6      1997   
25      name26    lastname26    Male   December         5      1999   
26      name27    lastname27  Female      March         4      1997   
27      name28    lastname28    Male   November        10      2000   
28      name29    lastname29  Female    October        10      1999   
29      name30    lastname30    Male        May        28      1999   
...        ...           ...     ...        ...       ...       ...   
2970  name2971  lastname2971  Female   February        25      1997   
2971  name2972  lastname2972    Male        May        14      1998   
2972  name2973  lastname2973  Female    October         9      1999   
2973  name2974  lastname2974  Female     August        12      1999   
2974  name2975  lastname2975  Female   November        18      1997   
2975  name2976  lastname2976  Female       July        24      1998   
2976  name2977  lastname2977  Female        May        26      1998   
2977  name2978  lastname2978  Female    October        26      1999   
2978  name2979  lastname2979    Male   February        13      1997   
2979  name2980  lastname2980    Male       July         3      1999   
2980  name2981  lastname2981  Female   February        17      1998   
2981  name2982  lastname2982    Male      March        28      2000   
2982  name2983  lastname2983    Male   December         3      1998   
2983  name2984  lastname2984    Male   November        13      2000   
2984  name2985  lastname2985  Female   February        23      1999   
2985  name2986  lastname2986  Female      March         2      1999   
2986  name2987  lastname2987  Female    October         6      1997   
2987  name2988  lastname2988  Female   February        20      1997   
2988  name2989  lastname2989    Male    January        17      1999   
2989  name2990  lastname2990  Female       July        14      1997   
2990  name2991  lastname2991  Female       July        27      2000   
2991  name2992  lastname2992    Male      March        26      1999   
2992  name2993  lastname2993  Female      April         1      2000   
2993  name2994  lastname2994    Male      April        10      1999   
2994  name2995  lastname2995 

# Exporting to CSV

In [39]:
final_recweek.to_csv('cleanrecweekdata3b.csv')

# Required Summary Statistics

#### These were the questions from 3A:

1. How many people were born in each month?
2. How many people were born on each day?
3. How many people were born in each year?
4. How many people come from each course?
5. How many people have numbers from Globe (0917 or 0927) and Smart (0918)? *Note: it's up to you how to format this output*

#### Additional Questions:
* How many Globe subscribers are: Male? Female?
* How many Smart subscribers are: Male? Female?

Answer these questions in an html file called **stats3b.html**. The format of the html is as follows (in template form, so you can use this as format string in your program, though feel free to modify with variable names if you find it easier to do so):


```
<html>
    <body>
         <h2>Summary Statistics</h2>
         <table>
             <tr><th>Stat</th><th>Value</th></tr>
             <tr><td>People born in each month</td><td>{}</td></tr>
             <tr><td>People born on each day</td><td>{}</td></tr>
             <tr><td>People born in each year</td><td>{}</td></tr>
             <tr><td>People coming from each course</td><td>{}</td></tr>
             <tr><td>People having numbers from Globe and Smart</td><td>{}</td></tr>
             <tr><td>Male Globe subscribers:</td><td>{}</td></tr>
             <tr><td>Female Globe subscribers:</td><td>{}</td></tr>
             <tr><td>Male Smart subscribers:</td><td>{}</td></tr>
             <tr><td>Female Smart subscribers:</td><td>{}</td></tr>
         </table>
    </body>
</html>
```

# Same Month

In [40]:
final_recweek.groupby(["birthmonth"])["firstname"].count()

birthmonth
April        267
August       241
December     276
February     232
January      270
July         249
June         259
March        246
May          273
November     277
October      178
September    232
Name: firstname, dtype: int64

In [41]:
month_count = final_recweek.groupby(["birthmonth"])["firstname"].count()
month_count = month_count.to_frame(name="count")
month_count.reset_index(inplace=True)
month_count

birthmonth  count
0       April    267
1      August    241
2    December    276
3    February    232
4     January    270
5        July    249
6        June    259
7       March    246
8         May    273
9    November    277
10    October    178
11  September    232

In [42]:
month_dict = {"January":1,
              "February":2,
              "March":3,
              "April":4,
              "May":5,
              "June":6,
              "July":7,
              "August":8,
              "September":9,
              "October":10,
              "November":11,
              "December":12}

In [43]:
month_fix = month_count.loc[:,"birthmonth"].apply(lambda x: re.sub(x,str(month_dict[x]), x) )
month_fix = month_fix.to_frame(name="new_index")
month_fix = month_fix.loc[:,"new_index"].apply(pd.to_numeric)


In [44]:
month_count = month_count.join(month_fix)
month_count = month_count.set_index("new_index")
month_count

birthmonth  count
new_index                  
4              April    267
8             August    241
12          December    276
2           February    232
1            January    270
7               July    249
6               June    259
3              March    246
5                May    273
11          November    277
10           October    178
9          September    232

In [45]:
month_count = month_count.sort_index()
month_count

birthmonth  count
new_index                  
1            January    270
2           February    232
3              March    246
4              April    267
5                May    273
6               June    259
7               July    249
8             August    241
9          September    232
10           October    178
11          November    277
12          December    276

# Same Day

In [46]:
day_count = final_recweek.groupby(["birthday"])["firstname"].count()
day_count = day_count.to_frame(name="count")
day_count.reset_index(inplace=True)
day_count

birthday  count
0          1    112
1          2    106
2          3     90
3          4    110
4          5    100
5          6     99
6          7     88
7          8    111
8          9     98
9         10    111
10        11    105
11        12     98
12        13    119
13        14    102
14        15    121
15        16    115
16        17    116
17        18    107
18        19    113
19        20     91
20        21    123
21        22    103
22        23    116
23        24    108
24        25    116
25        26    116
26        27    102
27        28    104

# Same Year

In [47]:
year_count = final_recweek.groupby(["birthyear"])["firstname"].count()
year_count = year_count.to_frame(name="count")
year_count.reset_index(inplace=True)
year_count

birthyear  count
0      1997    756
1      1998    746
2      1999    756
3      2000    380
4      2001    362

# Same Course

In [48]:
course_count = final_recweek.groupby(["course"])["firstname"].count()
course_count = course_count.to_frame(name="count")
course_count.reset_index(inplace=True)
course_count

course  count
0  BS Communications Technology    589
1        BS IT Entrepreneurship    590
2           BS Legal Management    585
3                 BS Management    629
4     BS Management Engineering    607

# Globe or Smart

In [49]:
carrier = {"0917":"Globe", "0927":"Globe", "0918":"Smart"}

In [50]:
final_recweek.loc[:,"phonenumber"].str[0:4].apply(lambda x: carrier[x])

0       Smart
1       Globe
2       Smart
3       Smart
4       Globe
5       Smart
6       Globe
7       Globe
8       Smart
9       Smart
10      Globe
11      Globe
12      Globe
13      Globe
14      Globe
15      Smart
16      Globe
17      Globe
18      Globe
19      Globe
20      Globe
21      Globe
22      Globe
23      Globe
24      Smart
25      Globe
26      Globe
27      Globe
28      Globe
29      Globe
        ...  
2970    Smart
2971    Globe
2972    Globe
2973    Globe
2974    Globe
2975    Globe
2976    Smart
2977    Smart
2978    Smart
2979    Smart
2980    Globe
2981    Globe
2982    Smart
2983    Globe
2984    Globe
2985    Globe
2986    Smart
2987    Globe
2988    Globe
2989    Globe
2990    Smart
2991    Globe
2992    Globe
2993    Globe
2994    Globe
2995    Globe
2996    Globe
2997    Globe
2998    Globe
2999    Smart
Name: phonenumber, Length: 3000, dtype: object

In [51]:
final_recweek["carrier"] = final_recweek.loc[:,"phonenumber"].str[0:4].apply(lambda x: carrier[x])
final_recweek


firstname      lastname  gender birthmonth  birthday birthyear  \
0        name1     lastname1  Female   November        26      1998   
1        name2     lastname2  Female        May        26      2001   
2        name3     lastname3  Female        May        16      1997   
3        name4     lastname4    Male   December         9      1997   
4        name5     lastname5  Female  September         5      1997   
5        name6     lastname6  Female      March         2      1999   
6        name7     lastname7  Female   November        10      1998   
7        name8     lastname8    Male     August        28      1999   
8        name9     lastname9    Male       July        10      1997   
9       name10    lastname10  Female  September        14      2001   
10      name11    lastname11    Male   December         8      1998   
11      name12    lastname12    Male        May         4      1997   
12      name13    lastname13  Female    January        28      1999   
13      name14    lastname14  Female    January        11      1999   
14      name15    lastname15    Male       June         6      1998   
15      name16    lastname16    Male      April        20      1999   
16      name17    lastname17  Female    January         3      1997   
17      name18    lastname18  Female      April         8      1997   
18      name19    lastname19    Male   December        28      1997   
19      name20    lastname20    Male      March        10      1997   
20      name21    lastname21  Female       July        13      1999   
21      name22    lastname22    Male  September        15      1999   
22      name23    lastname23    Male      April        15      1997   
23      name24    lastname24    Male    October         1      1997   
24      name25    lastname25    Male        May         6      1997   
25      name26    lastname26    Male   December         5      1999   
26      name27    lastname27  Female      March         4      1997   
27      name28    lastname28    Male   November        10      2000   
28      name29    lastname29  Female    October        10      1999   
29      name30    lastname30    Male        May        28      1999   
...        ...           ...     ...        ...       ...       ...   
2970  name2971  lastname2971  Female   February        25      1997   
2971  name2972  lastname2972    Male        May        14      1998   
2972  name2973  lastname2973  Female    October         9      1999   
2973  name2974  lastname2974  Female     August        12      1999   
2974  name2975  lastname2975  Female   November        18      1997   
2975  name2976  lastname2976  Female       July        24      1998   
2976  name2977  lastname2977  Female        May        26      1998   
2977  name2978  lastname2978  Female    October        26      1999   
2978  name2979  lastname2979    Male   February        13      1997   
2979  name2980  lastname2980    Male       July         3      1999   
2980  name2981  lastname2981  Female   February        17      1998   
2981  name2982  lastname2982    Male      March        28      2000   
2982  name2983  lastname2983    Male   December         3      1998   
2983  name2984  lastname2984    Male   November        13      2000   
2984  name2985  lastname2985  Female   February        23      1999   
2985  name2986  lastname2986  Female      March         2      1999   
2986  name2987  lastname2987  Female    October         6      1997   
2987  name2988  lastname2988  Female   February        20      1997   
2988  name2989  lastname2989    Male    January        17      1999   
2989  name2990  lastname2990  Female       July        14      1997   
2990  name2991  lastname2991  Female       July        27      2000   
2991  name2992  lastname2992    Male      March        26      1999   
2992  name2993  lastname2993  Female      April         1      2000   
2993  name2994  lastname2994    Male      April        10      1999   
2994  name2995  lastname2995 

In [52]:
phone_count = final_recweek.groupby(["carrier","gender"])["firstname"].count()
phone_count

carrier  gender
Globe    Female     984
         Male      1061
Smart    Female     494
         Male       461
Name: firstname, dtype: int64

In [53]:
globe_female = phone_count[("Globe","Female")]
globe_male = phone_count[("Globe","Male")]
smart_female = phone_count[("Smart","Female")]
smart_male = phone_count[("Smart","Male")]


In [54]:
gender_count = phone_count.to_frame(name="count")
gender_count.reset_index(inplace=True)
gender_count

carrier  gender  count
0   Globe  Female    984
1   Globe    Male   1061
2   Smart  Female    494
3   Smart    Male    461

In [55]:
carrier_count = gender_count.loc[:,["carrier","count"]]
carrier_count = carrier_count.set_index("carrier").sum(level="carrier")
carrier_count.reset_index(inplace=True)
carrier_count

carrier  count
0   Globe   2045
1   Smart    955

# Summary Stats

In [56]:
from IPython.core.display import HTML

html = """
<html>
    <body>
         <h2>Summary Statistics</h2>
         <table>
             <tr><th>Stat</th><th>Value</th></tr>
             <tr><td>People born in each month</td><td>{month_count} </td></tr>
             <tr><td>People born on each day</td><td>{day_count} </td></tr>
             <tr><td>People born in each year</td><td>{year_count} </td></tr>
             <tr><td>People coming from each course</td><td>{course_count} </td></tr>
             <tr><td>People having numbers from Globe and Smart</td><td>{carrier_count}</td></tr>
             <tr><td>Male Globe subscribers:</td><td>{globe_male}</td></tr>
             <tr><td>Female Globe subscribers:</td><td>{globe_female}</td></tr>
             <tr><td>Male Smart subscribers:</td><td>{smart_male}</td></tr>
             <tr><td>Female Smart subscribers:</td><td>{smart_female}</td></tr>
         </table>
    </body>
</html>
"""

html_output = html.format(month_count = month_count,
                          day_count = day_count,
                          year_count = year_count,
                          course_count = course_count,
                          carrier_count = carrier_count,
                          globe_male = globe_male,
                          globe_female = globe_female,
                          smart_male = smart_male,
                          smart_female = smart_female                          
                         )

HTML(html_output)


# Creating an HTML

## Months

In [57]:
month_count.loc[:,["birthmonth","count"]].apply(lambda x: x[0]+str(x[1]), axis=1)


new_index
1       January270
2      February232
3         March246
4         April267
5           May273
6          June259
7          July249
8        August241
9     September232
10      October178
11     November277
12     December276
dtype: object

In [58]:
month_string = month_count.loc[:,["birthmonth","count"]].apply(lambda x: """<div class="divTableRow"><div class="divTableCell">{}</div><div class="divTableCell">{}</div></div>""".format(x[0],str(x[1])), axis=1).str.cat(sep="")
month_string


'<div class="divTableRow"><div class="divTableCell">January</div><div class="divTableCell">270</div></div><div class="divTableRow"><div class="divTableCell">February</div><div class="divTableCell">232</div></div><div class="divTableRow"><div class="divTableCell">March</div><div class="divTableCell">246</div></div><div class="divTableRow"><div class="divTableCell">April</div><div class="divTableCell">267</div></div><div class="divTableRow"><div class="divTableCell">May</div><div class="divTableCell">273</div></div><div class="divTableRow"><div class="divTableCell">June</div><div class="divTableCell">259</div></div><div class="divTableRow"><div class="divTableCell">July</div><div class="divTableCell">249</div></div><div class="divTableRow"><div class="divTableCell">August</div><div class="divTableCell">241</div></div><div class="divTableRow"><div class="divTableCell">September</div><div class="divTableCell">232</div></div><div class="divTableRow"><div class="divTableCell">October</div><d

## Days

In [59]:
day_count.loc[:,["birthday","count"]].apply(lambda x: str(x[0])+str(x[1]), axis=1)


0      1112
1      2106
2       390
3      4110
4      5100
5       699
6       788
7      8111
8       998
9     10111
10    11105
11     1298
12    13119
13    14102
14    15121
15    16115
16    17116
17    18107
18    19113
19     2091
20    21123
21    22103
22    23116
23    24108
24    25116
25    26116
26    27102
27    28104
dtype: object

In [60]:
day_string = day_count.loc[:,["birthday","count"]].apply(lambda x: """<div class="divTableRow"><div class="divTableCell">{}</div><div class="divTableCell">{}</div></div>""".format(x[0],str(x[1])), axis=1).str.cat(sep="")
day_string


'<div class="divTableRow"><div class="divTableCell">1</div><div class="divTableCell">112</div></div><div class="divTableRow"><div class="divTableCell">2</div><div class="divTableCell">106</div></div><div class="divTableRow"><div class="divTableCell">3</div><div class="divTableCell">90</div></div><div class="divTableRow"><div class="divTableCell">4</div><div class="divTableCell">110</div></div><div class="divTableRow"><div class="divTableCell">5</div><div class="divTableCell">100</div></div><div class="divTableRow"><div class="divTableCell">6</div><div class="divTableCell">99</div></div><div class="divTableRow"><div class="divTableCell">7</div><div class="divTableCell">88</div></div><div class="divTableRow"><div class="divTableCell">8</div><div class="divTableCell">111</div></div><div class="divTableRow"><div class="divTableCell">9</div><div class="divTableCell">98</div></div><div class="divTableRow"><div class="divTableCell">10</div><div class="divTableCell">111</div></div><div class="

## Years

In [61]:
year_count.loc[:,["birthyear","count"]].apply(lambda x: str(x[0])+str(x[1]), axis=1)


0    1997756
1    1998746
2    1999756
3    2000380
4    2001362
dtype: object

In [62]:
year_string = year_count.loc[:,["birthyear","count"]].apply(lambda x: """<div class="divTableRow"><div class="divTableCell">{}</div><div class="divTableCell">{}</div></div>""".format(x[0],str(x[1])), axis=1).str.cat(sep="")
year_string


'<div class="divTableRow"><div class="divTableCell">1997</div><div class="divTableCell">756</div></div><div class="divTableRow"><div class="divTableCell">1998</div><div class="divTableCell">746</div></div><div class="divTableRow"><div class="divTableCell">1999</div><div class="divTableCell">756</div></div><div class="divTableRow"><div class="divTableCell">2000</div><div class="divTableCell">380</div></div><div class="divTableRow"><div class="divTableCell">2001</div><div class="divTableCell">362</div></div>'

## Courses

In [63]:
course_count.loc[:,["course","count"]].apply(lambda x: str(x[0])+str(x[1]), axis=1)


0    BS Communications Technology589
1          BS IT Entrepreneurship590
2             BS Legal Management585
3                   BS Management629
4       BS Management Engineering607
dtype: object

In [64]:
course_string = course_count.loc[:,["course","count"]].apply(lambda x: """<div class="divTableRow"><div class="divTableCell">{}</div><div class="divTableCell">{}</div></div>""".format(x[0],str(x[1])), axis=1).str.cat(sep="")
course_string


'<div class="divTableRow"><div class="divTableCell">BS Communications Technology</div><div class="divTableCell">589</div></div><div class="divTableRow"><div class="divTableCell">BS IT Entrepreneurship</div><div class="divTableCell">590</div></div><div class="divTableRow"><div class="divTableCell">BS Legal Management</div><div class="divTableCell">585</div></div><div class="divTableRow"><div class="divTableCell">BS Management</div><div class="divTableCell">629</div></div><div class="divTableRow"><div class="divTableCell">BS Management Engineering</div><div class="divTableCell">607</div></div>'

## Carriers

### Globe/Smart

In [65]:
carrier_count.loc[:,["carrier","count"]].apply(lambda x: str(x[0])+str(x[1]), axis=1)

0    Globe2045
1     Smart955
dtype: object

In [66]:
carrier_string = carrier_count.loc[:,["carrier","count"]].apply(lambda x: """<div class="divTableRow"><div class="divTableCell">{}</div><div class="divTableCell">{}</div></div>""".format(x[0],str(x[1])), axis=1).str.cat(sep="")
carrier_string


'<div class="divTableRow"><div class="divTableCell">Globe</div><div class="divTableCell">2045</div></div><div class="divTableRow"><div class="divTableCell">Smart</div><div class="divTableCell">955</div></div>'

### By Gender

In [67]:
gender_count.loc[:,["carrier","gender","count"]].apply(lambda x: str(x[0])+str(x[1]+str(x[2])), axis=1)


0    GlobeFemale984
1     GlobeMale1061
2    SmartFemale494
3      SmartMale461
dtype: object

In [68]:
gender_string = gender_count.loc[:,["carrier","gender","count"]].apply(lambda x: """<div class="divTableRow"><div class="divTableCell">{}</div><div class="divTableCell">{}</div><div class="divTableCell">{}</div></div>""".format(str(x[0]),str(x[1]),str(x[2])), axis=1).str.cat(sep="")
gender_string


'<div class="divTableRow"><div class="divTableCell">Globe</div><div class="divTableCell">Female</div><div class="divTableCell">984</div></div><div class="divTableRow"><div class="divTableCell">Globe</div><div class="divTableCell">Male</div><div class="divTableCell">1061</div></div><div class="divTableRow"><div class="divTableCell">Smart</div><div class="divTableCell">Female</div><div class="divTableCell">494</div></div><div class="divTableRow"><div class="divTableCell">Smart</div><div class="divTableCell">Male</div><div class="divTableCell">461</div></div>'

## Compilation

In [69]:
html_file = """
<html>
    <link rel="stylesheet" type="text/css" href="CSS_FILE copy.css" />
    <div>
        <div align="center"><h1>RecWeek 2019</h1></div>
        <div class="container">
            <div id="bl-main" class="bl-main">
                <section>
                    <div class="bl-box">
                        <h2>
                            same birth month
                        </h2>
                        <div class="bl-content">
                            &nbsp;
                        </div>
                        <div class="divTable Mica">
                            <div class="divTableHeading">       
                                <div class="divTableHead">MONTH</div>
                                <div class="divTableHead">COUNT</div>
                            </div>
                            <div class="divTableBody">
                            {}
                            </div>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="bl-box">
                        <h2>
                            same birth day
                        </h2>
                        <div class="divTable Mica">
                            <div class="divTableHeading">
                                <div class="divTableHead">DAY</div>
                                <div class="divTableHead">COUNT</div>
                            </div>
                            <div class="divTableBody">
                            {}
                            </div>
                        </div>
                    </div>
                    <div class="bl-content">
                        &nbsp;
                    </div>
                </section>
                <section>
                    <div class="bl-box">
                        <h2>
                            same birth year
                        </h2>
                        <div class="divTable Mica">
                            <div class="divTableHeading">
                                <div class="divTableHead">YEAR</div>
                                <div class="divTableHead">COUNT</div>
                            </div>
                            <div class="divTableBody">
                            {}
                            </div>
                        </div>
                    </div>
                    <div class="bl-content">
                        &nbsp;
                    </div>
                </section>
                <section id="bl-work-section">
                    <div class="bl-box">
                        <h2>
                            same course
                        </h2>
                        <div class="divTable Mica">
                            <div class="divTableHeading">
                                <div class="divTableHead">COURSE</div>
                                <div class="divTableHead">COUNT</div>
                            </div>
                            <div class="divTableBody">
                            {}
                            </div>
                        </div>
                    </div>
                    <div class="bl-content">
                        <div class="bl-content">
                            &nbsp;
                        </div>
                    </div>
                </section>
                <section id="bl-work-section">
                    <div class="bl-box">
                        <h2>
                            same network
                        </h2>
                        <div class="divTable Mica">
                            <div class="divTableHeading">
                                <div class="divTableHead">CARRIER</div>
                                <div class="divTableHead">COUNT</div>
                            </div>
                            <div class="divTableBody">
                            {}
                            </div>
                        </div>
                        <div class="divTable Mica">
                            <div class="divTableHeading">
                                <div class="divTableHead">CARRIER</div>
                                <div class="divTableHead">GENDER</div>
                                <div class="divTableHead">COUNT</div>
                            </div>
                            <div class="divTableBody">
                            {}
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</html>
"""

In [70]:
html_file = html_file.format(month_string,
              day_string,
              year_string,
              course_string,
              carrier_string,
              gender_string)
html_file

'\n<html>\n    <link rel="stylesheet" type="text/css" href="CSS_FILE copy.css" />\n    <div>\n        <div align="center"><h1>RecWeek 2019</h1></div>\n        <div class="container">\n            <div id="bl-main" class="bl-main">\n                <section>\n                    <div class="bl-box">\n                        <h2>\n                            same birth month\n                        </h2>\n                        <div class="bl-content">\n                            &nbsp;\n                        </div>\n                        <div class="divTable Mica">\n                            <div class="divTableHeading">       \n                                <div class="divTableHead">MONTH</div>\n                                <div class="divTableHead">COUNT</div>\n                            </div>\n                            <div class="divTableBody">\n                            <div class="divTableRow"><div class="divTableCell">January</div><div class="divTableCell">270

In [71]:
with open('stats3b.html',"w+") as file: 
    file.write(html_file)